# Generated by Django 6.0.3 on 2026-04-07 21:05

from pathlib import Path

from django.db import migrations


def load_seed_sql():
    base_dir = Path(__file__).resolve().parent.parent.parent
    sql_file = base_dir / "seed" / "store.sql"
    return sql_file.read_text()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_add_first_collection"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_seed_sql(),
            reverse_sql="""
                DELETE FROM store_product;
                DELETE FROM store_collection;
                DELETE FROM store_orderitem;
                DELETE FROM store_order;
                DELETE FROM store_customer;
            """,
        ),
    ]
