# Generated by Django 6.0.3 on 2026-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_collection_options_alter_customer_options"),
    ]

    operations = [
        migrations.RunSQL("""
        SELECT SETVAL('public.auth_group_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_group;
        SELECT SETVAL('public.auth_group_permissions_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_group_permissions;
        SELECT SETVAL('public.auth_permission_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_permission;
        SELECT SETVAL('public.auth_user_groups_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_user_groups;
        SELECT SETVAL('public.auth_user_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_user;
        SELECT SETVAL('public.auth_user_user_permissions_id_seq', COALESCE(MAX(id), 1) ) FROM public.auth_user_user_permissions;
        SELECT SETVAL('public.django_admin_log_id_seq', COALESCE(MAX(id), 1) ) FROM public.django_admin_log;
        SELECT SETVAL('public.django_content_type_id_seq', COALESCE(MAX(id), 1) ) FROM public.django_content_type;
        SELECT SETVAL('public.django_migrations_id_seq', COALESCE(MAX(id), 1) ) FROM public.django_migrations;
        SELECT SETVAL('public.likes_likeditem_id_seq', COALESCE(MAX(id), 1) ) FROM public.likes_likeditem;
        SELECT SETVAL('public.store_address_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_address;
        SELECT SETVAL('public.store_cart_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_cart;
        SELECT SETVAL('public.store_cartitem_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_cartitem;
        SELECT SETVAL('public.store_collection_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_collection;
        SELECT SETVAL('public.store_customer_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_customer;
        SELECT SETVAL('public.store_order_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_order;
        SELECT SETVAL('public.store_orderitem_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_orderitem;
        SELECT SETVAL('public.store_product_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_product;
        SELECT SETVAL('public.store_product_promotions_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_product_promotions;
        SELECT SETVAL('public.store_promotion_id_seq', COALESCE(MAX(id), 1) ) FROM public.store_promotion;
        SELECT SETVAL('public.tags_tag_id_seq', COALESCE(MAX(id), 1) ) FROM public.tags_tag;
        SELECT SETVAL('public.tags_taggeditem_id_seq', COALESCE(MAX(id), 1) ) FROM public.tags_taggeditem;
        """),
    ]
