# Generated by Django 6.0.4 on 2026-04-25 20:54


from pathlib import Path

from django.db import migrations


def load_seed_sql():
    base_dir = Path(__file__).resolve().parent.parent.parent
    sql_file = base_dir / "seed" / "orders.sql"
    return sql_file.read_text()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_customer_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_seed_sql(),
            reverse_sql="""
                DELETE FROM store_orderitem;
                DELETE FROM store_order;
                DELETE FROM store_customer;
                DELETE FROM core_user;
            """,
        ),
    ]
