# Generated by Django 6.0.3 on 2026-04-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_seed_store_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
