# Generated by Django 6.0.3 on 2026-04-19 10:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_address_customer_alter_address_zip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE store_cart DROP COLUMN id CASCADE;",
            reverse_sql="ALTER TABLE store_cart ADD COLUMN id bigint;",
        ),
        migrations.AddField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                primary_key=True,
                default=uuid.uuid4,
                editable=False,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                to="store.cart",
                on_delete=models.CASCADE,
                related_name="cartitems",
            ),
        ),
    ]
